### ISSUE TITLE
README ROM1 dump size update

### ISSUE THREAD

**Issue by ManuBlack** [F0bes/biosdrain#11]
Hello, I have used the latest version (v2.1.0) to dump the BIOS. Based on current README, under section _Uninteresting info_, I was expecting a file size of 512 kB for ROM1 so I was surprised when I got 4096 kB file, thinking that the process had somehow failed in my model (SCPH-77004). 

Then I noticed in commit 49406d09fa43c126ba7bb9702788d0eda1024401 that the dump file size has indeed changed hence the process was successful. Please update the relevant information as it is misleading.

**Comment by F0bes** [comment]
Thanks, fixed.
