### ISSUE TITLE
SCPH 39001: Failed to open 0 file

### ISSUE THREAD

**Issue by ToTheXtreme64** [F0bes/biosdrain#22]
Trying to dump a PS2 SCPH 39001 model, with biosdrain version 2.2.0 and I get the error message failed to open 0 file, with nothing saved to the USB drive afterwards. Any help would be greatly appreciated. 
![IMG_0221](https://github.com/user-attachments/assets/7d328f64-2f4c-4758-b8fe-13d6eefe2320)

**Comment by F0bes** [comment]
Can you try this release instead and see if it resolves that issue?
https://github.com/F0bes/biosdrain/releases/tag/v2.1.3

**Comment by ToTheXtreme64** [comment]
With version 2.1.3 I get a different error now. I get USB not found, and HOST is not available, not continuing. I also double checked and my USB drive is formatted to FAT32.

**Comment by F0bes** [comment]
You have the same issue as #23 
Like I said there, if the PS2SDK USB drivers can't detect your drive, there's nothing I can really do but try and fix the driver, which I just don't have the time for currently.

**Comment by ToTheXtreme64** [comment]
I tried with version 2.1.1 and it works perfectly now.
