### ISSUE TITLE
SCPH-50001 taking forever to dump

### ISSUE THREAD

**Issue by SavantSusi** [F0bes/biosdrain#23]
I have legit waited for an hour for it to dump. Takes a few seconds to load the text at first but then it gets stuck pretty much indefinitely. I put the elf at the root of the usb drive and loaded it with uloader. I have tried both a 8gb fat32 and a 4gb fat16 drive and both lead to the same outcome. One of my USBs lights up when a read/write operation occurs and it has been off for quite a while. As far as I know, my system is in complete working condition with no issues whatsoever.

![IMG_2616](https://github.com/user-attachments/assets/9e056dcc-b6e0-43d4-ab2c-1155256e3752)

**Comment by F0bes** [comment]
Can you try formatting at fat32 again and using this release instead?

https://github.com/F0bes/biosdrain/releases/tag/v2.1.3

**Comment by SavantSusi** [comment]
Ok, tried that and now it says "usb is not found, host is not available, not continuing". I even tried shinking the parition down to 1gb

**Comment by F0bes** [comment]
Unfortunately I'm at the mercy of the PS2SDK USB drivers. I don't do anything fancy but load them and see if the filesystem is present.

**Comment by SavantSusi** [comment]
hasn't it worked before on other models/versions?

**Comment by F0bes** [comment]
It's most likely to do with your USB drive(s).

**Comment by SavantSusi** [comment]
So a vintage usb flash drive from like 20 years ago would be more suitable I guess, where'd you find one like that?

**Comment by SavantSusi** [comment]
used version 2.1.1 and it worked https://github.com/F0bes/biosdrain/releases/tag/v2.1.1

**Comment by F0bes** [comment]
Thanks, I'll look into it.

**Comment by ottendorfcipher** [comment]
I had the same issue with same fix. PNY 8 GB USB drive, if that helps. :) v.2.1.1 worked.

**Comment by Nicd** [comment]
Just wanted to give my own experience. I have an 8 GB Kingston DataTraveler USB stick, but 2.2.0 got stuck copying ROM0 (USB stick was flashing all night), 2.1.3 didn't find the USB, and 2.1.1 also got stuck.

Swapped the memory stick with a MicroSD card in a USB adapter and 2.2.0 worked first try. So it might also be your USB stick, as said earlier. :) Thanks for the tool!
