### ISSUE TITLE
biosdrain 2.0.0 doesn't even load up on SCPH-70004 and SCPH-75004

### ISSUE THREAD

**Issue by ghost** [F0bes/biosdrain#8]
Just tried biosdrain v2.0.0 with multiple USB on Sony PS2 SCPH-70004 and SCPH-75004 (both PAL) using uLaunchELF 4.43a.

Got a black screen without nothing else when launching it

Got to use [v1.0.0](https://github.com/F0bes/biosdrain/releases/tag/v1.0.0) to dump bios correctly

**Comment by F0bes** [comment]
Thanks for the report. I've turned 2.0.0 into a prerelease and the latest release is now back to 1.0.0.
Sorry for the inconvenience, I'll get to bug hunting :sweat_smile:

**Comment by ghost** [comment]
It's okay !
Hit me up if when you will have fixed it so I can test it and give you feedback again if needed

Good luck with it

**Comment by F0bes** [comment]
If anyone is curious, I've got the black-screen issue figured out, but the IOP toolchain has a regression that prevents the sysman IRX from loading. I'm awaiting for a fix there before I can test it properly and provide a working release :face_exhaling:

**Comment by F0bes** [comment]
Can you try [this latest release](https://github.com/F0bes/biosdrain/releases/tag/v2.0.1)?

**Comment by ghost** [comment]
I tested the [2.0.2](https://github.com/F0bes/biosdrain/releases/tag/v2.0.2) instead of 2.0.1

It worked on both PS2 !
